(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(abbrev-mode t)
 '(default-enable-multibyte-characters nil t)
 '(display-battery-mode t)
 '(display-time-day-and-date nil)
 '(display-time-mail-file (quote none))
 '(display-time-mode t)
 '(ecb-auto-activate f)
 '(ecb-auto-compatibility-check nil)
 '(ecb-layout-name "left15")
 '(ecb-layout-window-sizes (quote (("left15" (0.215 . 0.7735849056603774) (0.215 . 0.20754716981132076)))))
 '(ecb-options-version "2.32")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
 '(ecb-select-edit-window-on-redraw t)
 '(ecb-source-path (quote (("/" "/"))))
 '(ecb-tip-of-the-day nil)
 '(ecb-tree-buffer-style (quote image))
 '(ecb-vc-enable-support t)
 '(ecb-wget-setup (cons "wget" (quote cygwin)))
 '(ecb-windows-width 0.22)
 '(font-lock-global-modes t)
 '(global-font-lock-mode t)
 '(global-pabbrev-mode t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote left))
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(javascript-indent-level 2)
 '(only-global-abbrevs t)
 '(pabbrev-minimal-expansion-p t)
 '(paren-match-face (quote paren-face-match-light))
 '(paren-sexp-mode t)
 '(recentf-mode t)
 '(save-abbrevs nil)
 '(scroll-bar-mode nil)
 '(show-paren-mode t)
 '(standard-indent 2)
 '(tab-width 2)
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(vc-directory-exclusion-list (quote ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "{arch}" "log" "doc" "rails")))
 '(vc-dired-recurse nil)
 '(vc-dired-terse-display nil)
 '(vc-handled-backends (quote (RCS CVS SCCS Git Hg Arch MCVS)))
 '(vc-keep-workfiles t)
 '(version-control nil)
 '(winner-mode t nil (winner)))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "White" :foreground "Black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :family "apple-Monaco"))))
 '(erb-comment-delim-face ((t (:inherit erb-delim-face :foreground "lightgreen" :weight bold))))
 '(erb-comment-face ((t (:inherit erb-face :foreground "lightgreen" :weight bold))))
 '(erb-face ((t (:background "gray30"))))
 '(erb-out-delim-face ((t (:inherit erb-delim-face :foreground "pink3" :weight bold))))
 '(flymake-errline ((((class color)) (:background "pink1"))))
 '(flymake-warnline ((((class color)) (:background "lightblue2"))))
 '(ido-first-match ((t (:foreground "blue"))))
 '(ido-only-match ((((class color)) (:foreground "firebrick"))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "darkgreen"))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode ((nil (:background "gray34"))))
 '(yaml-tab-face ((((class color)) (:background "red" :inverse-video unspecified)))))
